### ISSUE TITLE
Tooltip needs to switch location relative to mouse by context

### ISSUE THREAD

**Issue by ArtPoon** [neherlab/flu_frequencies#9]
![image](https://user-images.githubusercontent.com/1109328/236488142-6f208ca2-7ee5-4f32-ad40-2b099ae08d0e.png)

**Comment by ArtPoon** [comment]
actually I think displaying the entire table has limited utility - the time interval (x-coordinate) is useful, but I think it would be more accessible to render the frequencies as a fixed position table (perhaps incorporated into the checkbox menu)?

**Comment by ArtPoon** [comment]
Ok this was fairly easy to fix:
```diff
diff --git a/web/src/components/Regions/RegionsPlot.tsx b/web/src/components/Regions/RegionsPlot.tsx
index 80e6489..436be21 100644
--- a/web/src/components/Regions/RegionsPlot.tsx
+++ b/web/src/components/Regions/RegionsPlot.tsx
@@ -20,7 +20,7 @@ import { RegionsPlotTooltip } from 'src/components/Regions/RegionsPlotTooltip'
 import { DateSlider } from 'src/components/Common/DateSlider'
 import { localeAtom } from 'src/state/locale.state'
 
-const allowEscapeViewBox = { x: false, y: true }
+const allowEscapeViewBox = { x: false, y: false }
 const tooltipStyle = { zIndex: 1000, outline: 'none' }
 
 interface LinePlotProps<T> {
diff --git a/web/src/components/Variants/VariantsPlot.tsx b/web/src/components/Variants/VariantsPlot.tsx
index d36695a..acb75cf 100644
--- a/web/src/components/Variants/VariantsPlot.tsx
+++ b/web/src/components/Variants/VariantsPlot.tsx
@@ -20,7 +20,7 @@ import { VariantsPlotTooltip } from 'src/components/Variants/VariantsPlotTooltip
 import { DateSlider } from 'src/components/Common/DateSlider'
 import { localeAtom } from 'src/state/locale.state'
 
-const allowEscapeViewBox = { x: false, y: true }
+const allowEscapeViewBox = { x: false, y: false }
 const tooltipStyle = { zIndex: 1000, outline: 'none' }
 
 interface LinePlotProps<T> {
```
Does setting this property to `false` have any unintended consequences though?

**Comment by ArtPoon** [comment]
The problem is that the tooltip occupies most of the plot area, making it difficult to view the trend lines.  I think the best solution is to embed the table data being displayed in the tooltip into the left interface box as proposed above.  Making new branch `iss9` to implement.

**Comment by ivan-aksamentov** [comment]
Transparent tooltip should be easy to implement with some styling to the custom tooltip 
content component and/or to the parent tooltip component coming from recharts.

**Comment by ArtPoon** [comment]
Ok I will give this a try in `plot-tweaks` branch

**Comment by ivan-aksamentov** [comment]
Showing values in the "locations" side bar list (the one with checkboxes) might be tricky to do technically, as, I think, there is no way to tap into recharts and tell what part of the plot is being hovered.

We might try the following:
 - in the tooltip component, grab the date (on x acis) being mousehovered and set this date into recoil atom
 - in the "locations" side bar list entry component, grab the date from the atom and 

Instead of the date, one could also "remember" the full row of data in the tooltip, so that no data lookup is necessary in the list component.

But I am very concerned about the performance of this kind of solutions. Recoil and similar state management libraries are not very well suitable for high-frequency updates, which can happen if mouse is swiped quickly. And this is obviously a hack.

**Comment by ivan-aksamentov** [comment]
@ArtPoon We probably should not overload the `plot-tweaks` branch. Let's make smaller branches/PRs focused on particular features instead. This is easy to review, to reason about utility and easier to accept/reject/modify, should our scientist have some feedback.

**Comment by ivan-aksamentov** [comment]
Another difficulty I realized with combining the checkbox sidebar with the data table is that the list is quite long, scrollable and ordered in a particular way. Which is not the same with data table. So a combination of 2 may make it difficult to use for either of the 2 purposes. 

One alternative could be to have another, separate widget, let's say as a right sidebar.

But most plot libraries I've seen by default implement data display in a tooltip for a reason. This seems to be what people expect in most cases. We might keep both options, toggleable.

**Comment by ArtPoon** [comment]
To make the tooltip more compact:
* removed the Total column (repetitive)
* simplified formatting for confidence interval
* abbreviated "Frequency" to "Freq."

![Screenshot from 2023-05-16 14-25-15](https://github.com/neherlab/flu_frequencies/assets/1109328/efe52aba-d193-4d99-883e-9378a59b38f1)

**Comment by ivan-aksamentov** [comment]
Sure. It's up to you; no strong preference here. I just thought a real preview will be more interesting than a screenshot. There's also "draft PRs" if you want to highlight work-in-progress status.

In my experience, issues are rarely checked if noone is pinged directly. If you want feedback from the team, feel free to also post screenshots / PR links / preview links on Slack. Preview link can go straight to a page you want to be tested). This way people can test and give feedback almost in real time. I think this would be especially nice and productive for the small, immediately visible tweaks you are proposing lately.
